name: CI

on:
  workflow_dispatch:

jobs:
  test:
    name: Test (with prebuilt OCI Image)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Get sample PKGBUILD
        run: wget https://github.com/hapakaien/plenti-bin/raw/f5ffaaee02a2119aa16f6b7a27e87e198e096b47/PKGBUILD

      - name: Running test
        uses: ./
        with:
          pkgver: '0.4.26'
          pkgrel: 2
          updpkgsums: true
          srcinfo: true

      - name: Show diff
        run: |
          ls -la
          cat PKGBUILD
